### ISSUE TITLE
Changelog ordenado al reves

### ISSUE THREAD

**Issue by PuercoPop** [culqi/culqi-php#10]
La manera usual de ordenar un CHANGELOG es de los cambios mas recientes hacia los mas antiguos. De esta manera el usuario al abrir el archivo ve primero los ultimos cambios. En este caso el archivo CHANGELOG.md esta ordenado de los cambios mas antiguos hacia los mas recientes.

**Comment by soporte-culqi** [comment]
Gracias por la sugerencia, lo estaremos corrigiendo a la brevedad.
