### ISSUE TITLE
Conflicto con proyectos en namespaces

### ISSUE THREAD

**Issue by gtux** [culqi/culqi-php#14]
Tengo mi proyecto usando namespaces en todo lado, y cuando establezco algún error en la creación de pago me salta un error PHP diciendo: 

```
PHP Fatal error:  Class 'InvalidParamsException' not found in /var/www/vhosts/inngresa.com/vendor/culqi/Culqi/Pago.php on line 159
```

**Comment by brayancruces** [comment]
Es normal ese issue cuando usas namespaces. Ello simplemente se soluciona añadiendo al inicio:  \ . Para acceder al espacio global.

`\InvalidParamsException`   

Referencia: http://php.net/manual/en/language.namespaces.global.php

**Comment by gtux** [comment]
Hola @brayancruces 
Efectivamente sería cosa de corregirlo así siempre que el error fuese en mi código, pero si te fijas en el mensaje de error dice que el error se da en la clase Pago de culqui, no en mi código, exactamente culqi/Culqi/Pago.php on line 159.

Si gustas puedes verlo aquí: https://github.com/culqi/culqi-php/blob/master/lib/Culqi/Pago.php#L159

Por otro lado, el error es porque en ningún lado se declara una clase InvalidParamsException.

**Comment by brayancruces** [comment]
¡Hola @gtux! Acabamos hacer el nuevo release (v1.2.1). 

Esta puede ser instalada via compose y soporta namespaces.
