### ISSUE TITLE
No se puede cargar para laravel 5.4

### ISSUE THREAD

**Issue by juans05** [culqi/culqi-php#20]
e intentado isntalar "culqi/culqi-php": "1.3.*" para la version de laravel 5.4 pero me da un error

**Comment by brayancruces** [comment]
Hola @juans05  Por favor, podrías tomar captura del error y adjuntarlo.

¡Gracias!  😄

**Comment by juans05** [comment]
no te preocupes ya lo solucione

gracias por la rapidez.

**Comment by edandy** [comment]
Me sale este error.
![image](https://cloud.githubusercontent.com/assets/1874673/23437695/01e8578c-fddd-11e6-9308-afb32da39309.png)

**Comment by brayancruces** [comment]
Hola @edandy, tienes el mismo issue de @juans05, estás intentando con Laravel ?  
Espero tu respuesta para poder ayudarte.

**Comment by brayancruces** [comment]
Hola @edandy 
Ejemplo: https://gist.github.com/brayancruces/9bfeeb1bf1755d8db5a9334ee0fcb472  

Adjunto un ejemplo de como se puede llamar a la biblioteca Culqi desde un controlador en Laravel. Al momento de querer utilizar Culqi, usar en la cabecera del controlador: 

`use Culqi\Culqi;`

Recordar también  utilizar en el composer.json, dentro de _require_:
`"culqi/culqi-php": "1.3.3"` 

Y luego hacer en tu consola `~composer update`.
