### ISSUE TITLE
Error en version 1.3.* con Laravel 5.1 LTS

### ISSUE THREAD

**Issue by dantelibralato** [culqi/culqi-php#21]
He probado con laravel del repo http://github.com/culqi/culqi-laravel, con la version 1.3.* y da el siguiente error:
![imagen](https://cloud.githubusercontent.com/assets/15239304/23861374/d6be14d4-07d7-11e7-9564-80b87757954f.png)

Este error no ocurre con la version 1.2.5, pero esta version no usa la V2 de culqi.

Revisando los archivos Culqi.php de las 2 versiones, veo muchas diferencias.
Por favor arreglarlo pronto ya que necesito migrar de la version 1.1.

Saludos.

**Comment by LizRuelas** [comment]
Hola @dantelibralato  Ya tenemos una libreria v2 de culqi para laravel ( https://github.com/LizRuelas/culqi-laravel-v2.git ) .

Te agradecería lo pruebes y nos comentes como te fue.

**Comment by dantelibralato** [comment]
@LizRuelas mismo error.

Usando:

- Oracle Linux 6.6
- Nginx 1.10.3
- PHP 5.6.30
- Laravel 5.4

![imagen](https://cloud.githubusercontent.com/assets/15239304/23879205/a6446ee2-0819-11e7-9f52-dbf41256e2b2.png)

Yo estoy usando Laravel 5.1 LTS.

**Comment by LizRuelas** [comment]
Hola, te agradecería que al momento de importar la librería en Laravel
hagan la siguiente corrección :

[image: Imagen integrada 1]

Quedo atenta

Saludos

2017-03-13 18:21 GMT-05:00 dantelibralato <notifications@github.com>:

**Comment by dantelibralato** [comment]
@LizRuelas no se ve la imagen.

![imagen](https://cloud.githubusercontent.com/assets/15239304/23879916/2c4b8710-081e-11e7-9d3d-98a8ad88f2af.png)

Saludos.

**Comment by ferbj** [comment]
Tengo también el mismo error no me reconoce el token, puedo saber que esta pasando?.. o es que hay una incompatibilidad con laravel?..

**Comment by marti1125** [comment]
@ferbj ya se corrigio el composer.json puede volver a descargarlo
https://packagist.org/packages/culqi/culqi-php

**Comment by brayancruces** [comment]
Hola a todos  :nerd_face:  , ¿Pueden intentar de nuevo?  Hemos lanzado un nuevo release con un pequeño fix en el composer.json.  


Saludos,

**Comment by dantelibralato** [comment]
@brayancruces ahora sale el siguiente error:

![imagen](https://cloud.githubusercontent.com/assets/15239304/24010312/7e17b950-0a45-11e7-90d9-9d7a1c2e943e.png)

Usando:

    Oracle Linux 6.6
    Nginx 1.10.3
    PHP 5.6.30
    Laravel 5.4

Tambien

    Windows 7
    Apache 2.4
    PHP 5.5.12
    Laravel 5.2

**Comment by ferbj** [comment]
@brayancruces  el mismo error que la pantalla anterior
FatalThrowableError in web.php line 24:
Class 'Culqi\Culqi\Culqi' not found

**Comment by brayancruces** [comment]
@ferbj y @dantelibralato 

Ejemplo: https://gist.github.com/brayancruces/9bfeeb1bf1755d8db5a9334ee0fcb472  

Adjunto un ejemplo de como se puede llamar a la biblioteca Culqi desde un controlador en Laravel. Al momento de querer utilizar Culqi, usar en la cabecera del controlador: 

`use Culqi\Culqi;`

Recordar también  utilizar en el composer.json, dentro de _require_:
`"culqi/culqi-php": "1.3.3"` 

Y luego hacer en tu consola `~composer update`.

**Comment by ferbj** [comment]
@brayancruces ahora porque cuando uso mi token me aparece esto ? .. 
{tipo: "error_parametro", codigo: "token_invalido", mensaje_usuario: "Contactar al comercio.",…}
codigo: "token_invalido"
mensaje: "El token enviado es inválido."
mensaje_usuario: "Contactar al comercio."
objeto: "error"
tipo:
"error_parametro"

a pesar que yo estoy con mi api key, lo unico que he hecho es cambiar de key de la api nada mas para poder utilizar el ejemplo?.. cual crees tu que este obviando? he probado con la llave pública (pk) y la llave privada (sk) y obtengo el mismo error..
