### ISSUE TITLE
Incidencia con Email desde formulario CheckOut

### ISSUE THREAD

**Issue by carlosjacomi** [culqi/culqi-php#24]
Estimados Buenas Tardes

 Tengo la siguiente incidencia tengo un formulario checkout con los datos básicos a cargar, monto, titulo, descripcion, etc.
![image](https://user-images.githubusercontent.com/30361724/32918256-d86b491a-caef-11e7-85d7-fb8f01799eac.png)

el tema esta en que cuando llevo el proceso a pago  usando el molde de (02-create-charge.php), el mismo no se trae el correo que coloco en el formulario anterior por lo tanto el pago no se completa viendo el ejemplo ustedes tienen alli un dato fijo ("email" => "test@culqi.com",)

como hago para traerme el email que se coloca dentro del formulario estandar?

Saludos y gracias de antemano por el apoyo

**Comment by LizRuelas** [comment]
Hola @carlosjacomi Cuando se crea el token usando Culqi Checkout culqi devuelve un objeto token
donde esta el id que se envía con ajax hacia el back end ( 02-create-charge.php ) ademas del id esta el campo email del objeto token. asi como envias el id del token puedes enviar por ajax el email del objeto token a tu back end y crear el cargo con ese email.

Saludos

**Comment by carlosjacomi** [comment]
Gracias Liz, intentare probando y te comento :)
