### ISSUE TITLE
Laravel 5.5 - Error de autenticación

### ISSUE THREAD

**Issue by ggalvez92** [culqi/culqi-php#25]
Estoy tratando de crear token y me sale "Error de autenticación - 401" . Ojala puedan ayudarme, gracias.

**Comment by marti1125** [comment]
posiblemente estes colocando mal la llave public
https://www.culqi.com/api/#/tokens#create

**Comment by ggalvez92** [comment]
Estoy usando la librería de PHP ($culqi->Tokens->create(....) )y uso la key pero de desarrollo

**Comment by marti1125** [comment]
ok, entonces es otro detalle lo que pasa es que no puedes crear token directamente. Solo con el checkout o utilizando Culqi JS si necesitas ayuda con tu integración @LizRuelas te puede ayuda

**Comment by ggalvez92** [comment]
en Laravel ya logré realizar los cargos, ahora tengo problemas con ionic con la función de callback culqi

**Comment by LizRuelas** [comment]
Hola @ggalvez92  por el momento no tenemos un ejemplo para ionic
Saludos

**Comment by Adasso** [comment]
> ok, entonces es otro detalle lo que pasa es que no puedes crear token directamente. Solo con el checkout o utilizando Culqi JS si necesitas ayuda con tu integración @LizRuelas te puede ayuda

Pero si en tu documentación dice que puedes testear con esa función.
