### ISSUE TITLE
Culqi en Joomla

### ISSUE THREAD

**Issue by carlosjacomi** [culqi/culqi-php#27]
Hola estimados tienen pensado hacer un plugin o un repositorio para que se pueda integrar culqi a Joomla?

**Comment by brayancruces** [comment]
Hola @carlosjacomi , por el momento no hay planes de liberar una versión gratuita para Joomla. 

Por otro lado, hay otros desarrolladores que han desarrollado versiones (de paga) para extensiones especificas de shopping cart. 

https://www.j2store.org/extensions/payment-plugins/culqi-payment.html
