### ISSUE TITLE
Los nombres de las variables son intelegibles

### ISSUE THREAD

**Issue by jpscaletti** [culqi/culqi-php#3]
Estoy intentando crear una versión en Python de la biblioteca pero los nombres de las variables hacen *mucho* más dificil entender que está haciendo el código, por ejemplo:

```php
function crearDatospago($sp821fb9, $sp37cd46=null)
```

¿Qué son los parámetros? Es un misterio. ¿Están ofuscados a propósito? Deberían cambiarlos a algo como esto:

```php
function crearDatospago($datos_venta, $extra=null)
```

(y estoy adivinando que esos son los nombres correctos)

**Comment by carlosmoraleseguia** [comment]
Hola JP,
la libreria de PHP esta ofuscada. 

Escribeme a mi email carlos.morales@culqi.com, para tratar el tema de la libreria que quieres desarrollar y poder guiarte, un abrazo.

**Comment by jpscaletti** [comment]
Gracias por la oferta, Carlos.
Sin embargo **no tiene ningún sentido** ofuscar su código en este caso:

1. Es una biblioteca para conectarse a su servicio, el que me imagino quieren que la gente use. ¿Acaso pretenden tener que escribir ustedes mismos adaptadores para cada lenguaje actual y futuro?

2. Es más dificil decifrarlo pero no es, ni de lejos, imposible. Cualquiera con el tiempo disponible podría hacerlo. Entonces no protege realmente nada. Si alguien busca un bug para explotarlo, lo decifrará de todos modos.

3. Mientras más dificil sea de interpretar, más improbable es que alguien bienintencionado encuentre un bug y los proteja de (2)

4. Si llego a escribir una versión en Python, las variables tendrán nombres amigables y estará documentado de la forma más clara posible. Entonces los demás podrían usarla como referencia.

**Comment by alvaropereyra** [comment]
:+1:  a información no ofuscada :)

**Comment by carlosmoraleseguia** [comment]
Hola Juan Pablo,
las librerías que hemos puesto a disposición (PHP y Java) se conectan a una
API que aún no esta documentada al 100%.

Esta API servirá para que los desarrolladores puedan hacer su propia
librería en el lenguaje que dominen.

La estrategia actual, es que si vas a desarrollar en un lenguaje diferente
a las 2 librerías que hemos publicado nos lo comuniques para darte el Draft
del API.

**Comment by alvaropereyra** [comment]
Y si están en eso, sería muy genial que se refieran a su biblioteca correctamente como bibliteca y no "librería".

**Comment by hpneo** [comment]
Yo entiendo que al trabajar con tarjetas y pagos se necesite ser bastante sensible con la información que hacen pública, pero Stripe también lo hace y no se dedica a [ofuscar el código](https://github.com/stripe/stripe-php). De hecho, tienen 133 pull requests y no necesitan enviar correos para aceptar contribuciones.

Culqi está genial, pero creo que deberían relacionarse mejor con los devs (así como lo hace [Conekta](https://github.com/conekta) en México), porque al final eso nos beneficiará a todos.

**Comment by carlosmoraleseguia** [comment]
Totalmente de acuerdo Gustavo.

Pero comprendenos que en estos momentos estamos trabajando en la
publicación del API.

**Comment by hpneo** [comment]
Entiendo eso, y de nuevo, me parece genial lo que hacen (deben ser los primeros en Perú y eso es admirable), pero: 1) las APIs no están escritas en piedra, y 2) una biblioteca con comentarios y phpDocumentor sería suficiente para muchos.

Éxitos :)

**Comment by carlosmoraleseguia** [comment]
Gracias Gustavo por tu aporte y punto de vista, es valioso para nosotros.
