### ISSUE TITLE
Error entorno integración al crear cliente

### ISSUE THREAD

**Issue by emmanuelbarturen** [culqi/culqi-php#32]
Al crear un cliente recibo este error:
{"timestamp":1543186417322,"status":500,"error":"Internal Server Error","exception":"javax.persistence.EntityNotFoundException","message":"Unable to find com.culqi.api.database.model.TransactionRequest with id 2975865","path":"/api/v2/customers"}

**Comment by joelibaceta** [comment]
@emmanuelbarturen efectivamente era un error interno que se resolvió hace ya un tiempo, comentanos si vuelves a recibir este mensaje.
