### ISSUE TITLE
Endpoint request timed out : Al listar los cargos

### ISSUE THREAD

**Issue by gonzalesc** [culqi/culqi-php#33]
Hola
Estoy haciendo trayendo el listado de cargos de una cuenta de Culqi, aun ando haciendo pruebas en integración, pero eso me traer algunas veces bien y otras me muestra este error:

`"message": "Endpoint request timed out"`

Y no sólo hago pruebas en un browser sino también usando la aplicación postman y sucede lo mismo, a veces si trae correctamente el listado y otras no.

Sólo hay 10 cargos ahi.
Esto pasa porque es test? o sucede también en producción?

Saludos

**Comment by gonzalesc** [comment]
Este mensaje 
`"message": "Endpoint request timed out"`

Me aparece en algunas ocaciones pero en casi todas las consultas via API. Cuando creo un plan, cuando borro un plan, cuando obtengo la lista de pagos, cuando obtengo la lista de suscriptores... esta sucediendo en todo momento y como le digo, yo hago pruebas además con Postman y el resultado es el mismo, a veces si va bien otras no.

Aunque aun estoy haciendo pruebas con los keys de test.

Saludos

**Comment by cristofer239** [comment]
El dia de hoy haciendo pruebas en el entorno de integracion, tuve los mismos problemas, por lo que puedo observar, el httprequest que manda el servidor al api de culqi, recibe un timeout, y por lo que veo es que despues de 30 segundos el request lanza un timed out , revisando los logs en el dashboard de culqi , veo que los request son correctos pero tardan mas de 30 segundos, culqi logra obtener mi peticion y procesarla, el problema es que yo no tengo respuesta de ello por el problema del  timedout. Lo he probado a traves de web, y de postman tambien, pero en la mañana tardaban entre 5 a 3 segundos los request y ahora estan tardando mas , generando este inconveniente.

Saludos
