### ISSUE TITLE
Imposible conectar a Culqi API

### ISSUE THREAD

**Issue by mvegap** [culqi/culqi-php#34]
Hola, estoy teniendo un problema al crear el token mediante PHP. Ya lo he notificado y aún no recibo respuesta.

El response en el API Log es el siguiente: Imposible conectar a Culqi API:

{
  "object": "error",
  "type": "authentication_error",
  "merchant_message": "Tu código de comercio no está habilitado para realizar este tipo de peticiones. Contáctate con soporte@culqi.com para obtener mas información."
}

**Comment by mvegap** [comment]
@LizRuelas por favor tu apoyo.

**Comment by gonzalesc** [comment]
Que tal. Y lograste conectarlo? veo que esta fallando tb al listar los pagos y las suscripciones.

**Comment by mvegap** [comment]
@gonzalesc aún no, al parecer han realizado cambios en su API lo que está perjudicando algunos proyectos existentes. Ya lo he reportado y nada.

**Comment by gonzalesc** [comment]
@mvegap en tu caso tenes que llenar un autocuestionario, lo dice en su página misma: https://culqi.com/api/#/tokens#create

Yo tengo el mismo error pero en mi caso yo no uso PHP para generar el token sino JS y ya lo había hecho antes y nunca me falló pero desde hace unos días sí, ya les envié un correo, espero respondan.

Saludos

**Comment by LizRuelas** [comment]
Hola @mvegap deseas integrar Culqi en una ¿pagina web o aplicación móvil?

**Comment by mvegap** [comment]
@gonzalesc pero es extraño porque el mismo código lo estaba utilizando desde un inicio y no tenía problemas, al menos que hayn modificado sus políticas por seguridad y no se haya notificado. Gracias por el dato!

**Comment by mvegap** [comment]
@LizRuelas el problema que estoy teniendo es en la integración en una página web.

**Comment by joelibaceta** [comment]
@mvegap me parece que la tokenizacion debería realizarse únicamente desde frontend, a menos que tengas un comercio PCI Compliance.

**Comment by joelibaceta** [comment]
@mvegap por lo demás, el error por lo general se presenta cuando el comercio no se encuentra activado ( El botón activar comercio en el panel )

<img width="278" alt="Captura de Pantalla 2019-10-02 a la(s) 10 33 05" src="https://user-images.githubusercontent.com/864790/66058458-08170d80-e500-11e9-8dfc-752ad82e3fd0.png">

**Comment by mvegap** [comment]
> @mvegap me parece que la tokenizacion debería realizarse únicamente desde frontend, a menos que tengas un comercio PCI Compliance.

Gracias, pero en la documentación se debería especificar el tipo de error y la referencia a la cual apunta. Intentaré nuevamente.
