### ISSUE TITLE
No se puede crear token de cargo en Culqi API

### ISSUE THREAD

**Issue by zerojuls** [culqi/culqi-php#35]
Hola! Estoy teniendo problemas seguidos con culqi y no puedo crear el cargo del pago en el entorno de integración, a pesar que se crea el token de acceso, cada vez que envío un pago. Ya lo he notificado y aún no recibo respuesta.

Adjunto imágenes del api log y de la web y de la consola del navegador que muestra el error al crear el cargo y ni muestra código de respuesta alguno. 

![image001](https://user-images.githubusercontent.com/8573420/55637487-c98bda80-578a-11e9-8181-0aa9c55ecff2.png)
![image002](https://user-images.githubusercontent.com/8573420/55637492-cbee3480-578a-11e9-9ce1-f121b6334a93.png)
![image004](https://user-images.githubusercontent.com/8573420/55637495-ce508e80-578a-11e9-8014-8a2797483e73.png)

**Comment by joelibaceta** [comment]
Disculpa la tarda respuesta, @zerojuls aun tienes este problema?
