### ISSUE TITLE
Cambiar idioma Popup

### ISSUE THREAD

**Issue by gonzalesc** [culqi/culqi-php#36]
Hola.
Se puede cambiar el idioma del modal/popup de Culqi que sale por defecto?

Entiendo que estas son las variables que se setean al inicio:

```
<script>
  Culqi.settings({
    title: 'Culqi Store',
    currency: 'PEN',
    description: 'Polo/remera Culqi lover',
    amount: 3500
  });
</script>
```

Y quería saber si hay alguna para cambiar el idioma.

Saludos

**Comment by joelibaceta** [comment]
@gonzalesc este no es un canal de soporte general, sino esta destinado para la discusión sobre bugs issues o mejoras sobre el SDK alojado en este repositorio. ( Portal de ayuda https://culqi.zendesk.com/hc/es )
