### ISSUE TITLE
Problemas con control de errores

### ISSUE THREAD

**Issue by DavmanHack** [culqi/culqi-php#40]
use estas credenciales 

Diners Club | 3600 010000 0007 | 12/2024 | 820 | processing_error

y me sale el siguiente error

<br />
<b>Fatal error</b>:  Uncaught Culqi\Error\UnhandledError: {&quot;object&quot;:&quot;error&quot;,&quot;type&quot;:&quot;card_error&quot;,&quot;charge_id&quot;:&quot;chr_test_mGBHiVi0Pc7ASBPW&quot;,&quot;code&quot;:&quot;card_declined&quot;,&quot;decline_code&quot;:&quot;processing_error&quot;,&quot;merchant_message&quot;:&quot;Error de procesamiento. Ocurrió un error mientras procesabamos la compra. Contáctate con culqi.com/soporte para que te demos una solución.&quot;,&quot;user_message&quot;:&quot;Ocurrió un error mientras procesabamos tu compra. Contáctate con culqi.com/soporte para que te demos una solución.&quot;} in D:\xampp\htdocs\pagos\culqi\lib\Culqi\Client.php:54
Stack trace:
#0 c'/charges/', 'sk_test_wV2W34h...', Array)
#1 D:\xampp\htdocs\pagos\proceso.php(28): Culqi\Charges-&gt;create(Array)
#2 {main}
  thrown in <b>D:\xampp\htdocs\pagos\culqi\lib\Culqi\Client.php</b> on line <b>54</b><br />

**Comment by DavmanHack** [comment]
pero cuando ingreso la tarjeta

4111 1111 1111 1111 | 09/2020 | 123 | Venta exitosa

si me genera el json correctamente
{"duplicated":false,"object":"charge","id":"chr_test_3tn6FXJCGgoOcTAS","creation_date":1565069443000,"amount":5000,"amount_refunded":0,"current_amount":5000,"installments":1,"installments_amount":5000,"currency_code":"PEN","email":"dsoriano@loretosoft.com","description":"Dise\u00f1o web estatic2o","source":{"object":"token","id":"tkn_test_IdhB2ThTKhy1HFVh","type":"card","creation_date":1565069441000,"email":"dsoriano@loretosoft.com","card_number":"411111******1111","last_four":"1111","active":true,"iin":{"object":"iin","bin":"411111","card_brand":"Visa","card_type":"credito","card_category":"Cl\u00e1sica","issuer":{"name":"BBVA","country":"PERU","country_code":"PE","website":null,"phone_number":null},"installments_allowed":[2,4,6,8,10,12,3,5,7,9,24,48]},"client":{"ip":"190.43.126.192","ip_country":"Peru","ip_country_code":"PE","browser":"UNKNOWN","device_fingerprint":null,"device_type":"Escritorio"},"metadata":{"installments":"1"}},"outcome":{"type":"venta_exitosa","code":"AUT0000","merchant_message":"La operaci\u00f3n de venta ha sido autorizada exitosamente","user_message":"Su compra ha sido exitosa."},"fraud_score":11,"dispute":false,"capture":true,"reference_code":"FpSMg6W8hA","authorization_code":"MMKBY6","metadata":{},"total_fee":236,"fee_details":{"fixed_fee":{},"variable_fee":{"currency_code":"PEN","commision":0.0399,"total":200}},"total_fee_taxes":36,"transfer_amount":4764,"paid":false,"statement_descriptor":"CULQI*","transfer_id":null,"capture_date":1565069443000} 

cual puede ser el problema?

**Comment by fecori** [comment]
Hola @DavmanHack te respondi en este issue #26  saludos!

**Comment by joelibaceta** [comment]
@

**Comment by DavmanHack** [comment]
si, muchas gracias (Y)
