### ISSUE TITLE
Culqi\Error\AuthenticationError: Error de autenticación 

### ISSUE THREAD

**Issue by alederzz** [culqi/culqi-php#51]
Hola, estoy teniendo un error al realizar la integración, ya verifiqué todo y por mi lado lo veo bien.

Estoy usando Laravel 8 y Culqi php 1.5

```
Culqi\Error\AuthenticationError: Error de autenticación in file C:\laragon\www\alvaradoapp\vendor\culqi\culqi-php\lib\Culqi\Client.php on line 43

#0 C:\laragon\www\alvaradoapp\vendor\culqi\culqi-php\lib\Culqi\Charges.php(29): Culqi\Client->request('POST', '/charges/', 'sk_test_761xxxx...', Array)
#1 C:\laragon\www\alvaradoapp\app\Http\Controllers\DemoController.php(41): Culqi\Charges->create(Array)
#2 [internal function]: App\Http\Controllers\DemoController->post()
```

**ACTUALIZACIÓN:**
Si las consultas se envían a:
`https://api.culqi.com/v2 `
Los cargos se realizan sin problemas.

**Comment by renzocastillo** [comment]
@alederzz  me pasó lo mismo gracias por publicar esto, estuve contrastando las urls bases y vi que cuando pides el paquete por composer te salen éstas:

![image](https://user-images.githubusercontent.com/21372177/112377577-edb48f00-8cb3-11eb-9107-8efef9228932.png)

en cambios aquí en github en Culqi.php te salen las de la documentación:

![image](https://user-images.githubusercontent.com/21372177/112377885-3ff5b000-8cb4-11eb-82ee-8a00dc94afaa.png)

Pero veo que se hizo un commit porque esa url es para el recurso tokens, en tal caso deberían ir como otras constantes más y estar asociadas a ese recurso? O quedarían sólo las que indica la documentación en https://apidocs.culqi.com/#/tokens ?

**Comment by diaz315** [comment]
@renzocastillo , este era la solución , gracias.

**Comment by alederzz** [comment]
@renzocastillo así es. El error era ese, pero fue por que no tenia la versión correspondiente. Por alguna razón al momento de usar la última versión del paquete mediante composer no lo descargaba. Así que tuve que eliminar vendor y hacer composer install.
Pero lo repito el paquete estaba bien, el problema era mío.

culqi/culqi-php:  1.3.5
